version: "2"
volumes:
  workdir:
  xserver:
services:
  balena-player:
    build: .
    network_mode: host # host is only needed if you use the UDP broadcast feature
    ports:
      - 6666:6666
    volumes:
      - "workdir:/usr/src/app/media" # drive to mount the media to play
      - "xserver:/tmp/.X11-unix" # external xserver
    privileged: true
    devices:
      - /dev/dri
    group_add:
      - video
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.balena.features.supervisor-api: "1"
  xserver:
    image: gh_smarthomeagentur/xserver-aarch64 # x-server image. it may need to match your architecture
    restart: always
    privileged: true
    volumes:
      - "xserver:/tmp/.X11-unix"
