#!/bin/bash

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
export DISPLAY=:0
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket   dbus-send   --system   --print-reply   --dest=org.freedesktop.systemd1   /org/freedesktop/systemd1   org.freedesktop.systemd1.Manager.StartUnit string:"plymouth-quit.service" string:"replace"

sleep 1

sed -i 's/geteuid/getppid/' /usr/bin/vlc || true 
sed -i 's/geteuid/getppid/' /usr/local/bin/vlc || true 

sleep 1

echo "Wait for X11..."
while [ ! -e /tmp/.X11-unix/X${DISPLAY#*:} ]; do sleep 0.5; done

while true; do    
    npm run start
    echo "[VLC] restarting ..."
    sleep 10
done